# Favicon
favicon: 'theme-doku/img/favicon.ico'

# --------------------
# Navbar
# --------------------
navbar:
  # The URL of Logo which will be shown at navbar
  logo: 'theme-doku/img/logo.png'
  # If you Logo has no text, you can add title next to your logo.
  # Leave it as an empty string if you don't have
  logo_text: 'XX Mod Manager'
  links:
    zh-CN:
      - logo: # The font-awesome class name of the logo. Leave it blank if you don't need logo for this link
        text: '使用文档' # The logo text
        url: '/' # The url
      - logo: 'fa fa-plug'
        text: 'Scripts API' # The logo text
        url: '/api/' # The url
      - logo: 'fab fa-github' # The font-awesome class name of the logo
        # text: '' # The logo text
        url: 'https://github.com/xiaolinxiaozhu/XX-Mod-Manager' # The url

# --------------------
# Sidebar Items
# --------------------
sidebar:
  zh-CN: # Language
    docs: # Type bname
      level: 2 # 1 or 2
      items:
        # 1 level example:
        # - 开始使用 | start.html
        # - 配置文件 | config.html
        #
        # 2 level example:
        - 开始使用:
          - 安装 | install.html
          - 配置 | config.html
          - 导入你的第一个Mod | import.html
          - 自动化 | automation.html
          - 预设 | preset.html
        - 后续步骤:
          - 和XXMI协作 | workWithXXMI.html
          - 多游戏支持 | multiGame.html


github:
  repo: xiaolinxiaozhu/XX-Mod-Manager
  edit_on_github: true # true / false
  branch: main/ # set the branch you want to edit
  source_dir: hexo/ # set to '' if you want to use the default folder. Use docs/ if you want to use the repo/master/docs folder
