name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 使用最新的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build  # 执行打包命令

    - name: Build Electron app
      run: |
        npm run build
        # 在这里指定你希望的构建格式为 zip 格式
        npx electron-builder --win --x64 --config electron-builder.json

  release:
    runs-on: ubuntu-latest
    needs: build  # 确保在 build 完成后才运行 release

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload the release package to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: build/XX-Mod-Manager-win-x64.zip  # 发布 .zip 文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: rm -rf build/
